# Generated by Django 5.0.10 on 2025-02-06 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveIntegerField(help_text='The number of seats at the table (must be between 4 and 10).', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)], verbose_name='Number of seats')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is available')),
            ],
        ),
    ]
