# Generated by Django 5.0.10 on 2025-02-06 10:15

import restaurant_management.tables.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_seatcostsingleton_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCountSingleton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(help_text='Enter the number of your restaurant tables.', verbose_name='Table Count')),
            ],
            options={
                'verbose_name': 'TableCount',
                'verbose_name_plural': 'TableCount',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCEL', 'Cancel')], default=restaurant_management.tables.enums.ReservationStatusEnum['ACTIVE'], max_length=50, verbose_name='Reservation status'),
        ),
        migrations.AlterField(
            model_name='seatcostsingleton',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost per seat'),
        ),
    ]
