# Generated by Django 5.0.10 on 2025-02-06 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_remove_reservation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='seats_reserved',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
